Repository FBS-UNA/SCT_BACKEND, pull requests merged in 2023-04, with the labels that each got.

#27 Feature modificar peticion tramites asociados
  controllers/tramites-areas.controller.js
Labels: bug

#29 Refactorizacion tabla usuario roles
  .gitignore
  SCRIPT_BD.sql
  controllers/auth.controller.js
  routes/auth.js
Labels: Update

#32 Feature_Controller_Roles closed #30
  controllers/roles.controller.js
Labels: Update

#33 Feature_Crear_Testear_Cargar_Roles closed #31
  controllers/roles.controller.js
  index.js
  routes/roles.js
Labels: Update

#35 Feature_Crear_Testear_metodos_cargar_roles_usuarios closed #34
  controllers/usuarios.controller.js
  routes/usuarios.js
Labels: Update

#42 Hotfix estandar del reporte
  controllers/registroTramite.controller.js
  index.js
  routes/reporte.js
Labels: bug, Update

#43 Feature implementacion peticion reporte completo
  controllers/reporte.controller.js
  routes/reporte.js
Labels: user story
